### ISSUE TITLE
Feature Request: Show the matching groups

### ISSUE THREAD

**Issue by jottinger** [vgrazi/regex-tester-tool#1]
If the pattern is "(a)\s*(b)" and the input is "a b" then it matches the regex, yes, but it would be awesome to also see the groups displayed in the alternate window.

**Comment by vgrazi** [comment]
Would you envision this as a multi line listing in the auxiliary area (on the right), one line for each capture group match?

**Comment by jottinger** [comment]
Yeah... or a JTree, maybe, but I'd be happy with ANYTHING that displayed the actual capture groups.

**Comment by vgrazi** [comment]
Got it. For now, if you position the cursor after the parenthesis it will
highlight the capture group

**Comment by jottinger** [comment]
But it doesn't highlight the content *matched* by that group. In the regex data above, I want to see [a] and [b] highlighted separately so I can see what groups are emitted.

**Comment by vgrazi** [comment]
Yes it does show the content, it's highlighted in the lower window. Is that
not working for you? Which platform and Java version are you on?

**Comment by jottinger** [comment]
Java 8, it highlights the entire content no matter where the cursor is.

**Comment by vgrazi** [comment]
Should be fixed
